# Generated by Django 2.2.7 on 2019-12-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст')),
                ('active', models.BooleanField(default=True, verbose_name='вкл/выкл')),
                ('template', models.CharField(default='page/index.html', max_length=250, verbose_name='шаблон')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Cтраница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
