# Generated by Django 2.2.1 on 2019-11-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191127_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='paginated',
            field=models.PositiveIntegerField(default=5, verbose_name='количество новостей на странице'),
        ),
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.BooleanField(default=True, verbose_name='отображать?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='template',
            field=models.CharField(default='blog/single_post.html', max_length=500, verbose_name='шаблон'),
        ),
    ]
