# Generated by Django 2.2.7 on 2019-12-07 07:44

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='имя')),
                ('is_auth', models.BooleanField(default=True, verbose_name='для зарегистрированных?')),
                ('active', models.BooleanField(default=True, verbose_name='вкл/выкл')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('title', models.CharField(max_length=250, verbose_name='заголовок')),
                ('status', models.BooleanField(default=True, verbose_name='вкл/выкл')),
                ('is_auth', models.BooleanField(default=True, verbose_name='для зарегистрированных?')),
                ('anchor', models.CharField(max_length=250, verbose_name='якорь')),
                ('url', models.URLField(max_length=250, verbose_name='ссылка на внешний ресур')),
                ('active', models.BooleanField(default=True, verbose_name='вкл/выкл')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Menu', verbose_name='меню')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.MenuItem', verbose_name='родительская категория')),
            ],
            options={
                'verbose_name': 'Пункты меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
